# Generated by Django 5.1.6 on 2025-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_jmeno_customuser_pohlavi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jmeno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pohlavi',
            field=models.CharField(choices=[('muz', 'muz'), ('zena', 'zena')], max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prijmeni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trida',
            field=models.CharField(max_length=3),
        ),
    ]
