# Generated by Django 5.1.6 on 2025-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('ucitel', 'Ucitel'), ('admin', 'Admin')], default='student', max_length=15),
        ),
    ]
