# Generated by Django 5.1.6 on 2025-02-06 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_type_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Použíjte školní email', regex='^[a-zA-Z0-9._%+-]+@purkynka\\.cz$')]),
        ),
    ]
