# Generated by Django 5.1.6 on 2025-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pohlavi',
            field=models.CharField(choices=[('muz', 'Žena'), ('zena', 'Muž'), ('jine', 'Nechci uvádět')], default='jine', max_length=4),
        ),
    ]
