# Generated by Django 5.1.6 on 2025-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trida',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
