# Generated by Django 5.1.6 on 2025-02-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('navrhovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navrzene_prace', to=settings.AUTH_USER_MODEL)),
                ('zpracovatel', models.OneToOneField(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zpracovana_prace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
