# Generated by Django 5.1.6 on 2025-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='popis',
            field=models.TextField(default='Popis této práce není uveden.', max_length=255),
        ),
    ]
