# Generated by Django 5.1.6 on 2025-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='schvaleno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='popis',
            field=models.TextField(),
        ),
    ]
