# Generated by Django 5.1.6 on 2025-02-10 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_schvalovatel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='schvalovatel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ucitel'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schvalene_prace', to=settings.AUTH_USER_MODEL),
        ),
    ]
